/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report that the service is running, and which release is running it.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guestbook-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Guestbook Entries
         * @description One page of entries, with how many match and how many the book holds.
         *
         *     The four parameters are bounded here rather than in the service, because
         *     every one of them is a fact about *this request* -- and FastAPI turns each
         *     bound into the standard 422 the frontend already normalises
         *     (`frontend/src/api/problem.ts`). A bad `sort` is therefore a refusal a
         *     caller can act on rather than a silent fall back to the default.
         */
        get: operations["list_guestbook_entries_api_guestbook_entries_get"];
        put?: never;
        /**
         * Create Guestbook Entry
         * @description Add an entry. The length and emptiness rules refuse with 422 in Pydantic.
         */
        post: operations["create_guestbook_entry_api_guestbook_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guestbook-entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Guestbook Entry
         * @description One entry by id.
         *
         *     Raises:
         *         HTTPException: 404 if no entry with `entry_id` exists.
         */
        get: operations["read_guestbook_entry_api_guestbook_entries__entry_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Guestbook Entry
         * @description Remove an entry permanently.
         *
         *     Raises:
         *         HTTPException: 404 if no entry with `entry_id` exists, so deleting the
         *             same id twice refuses the second time instead of reporting success.
         */
        delete: operations["delete_guestbook_entry_api_guestbook_entries__entry_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Guestbook Entry
         * @description Change an entry's author, its message, or both.
         *
         *     Raises:
         *         HTTPException: 422 if the body sets no field; 404 if no entry with
         *             `entry_id` exists.
         */
        patch: operations["update_guestbook_entry_api_guestbook_entries__entry_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * GuestbookEntryCreate
         * @description Request contract for `POST /api/guestbook-entries`.
         */
        GuestbookEntryCreate: {
            /** Author */
            author: string;
            /** Message */
            message: string;
        };
        /**
         * GuestbookEntryPage
         * @description Response contract for `GET /api/guestbook-entries`: one page and two counts.
         *
         *     An envelope rather than a bare array, because a page cannot imply either
         *     number a paged screen has to state. `items` is what fits; `total` is how many
         *     entries answer the question that was asked; `total_all` is how big the book
         *     is regardless of the question.
         *
         *     **The two counts are different facts and the screen shows both at once.** The
         *     header says how many entries exist; the line under the search box says how
         *     many the current search matched. Deriving either from `len(items)` is the
         *     defect `e2e/harness/list_response.py` was written about: 2 is a plausible
         *     number of rows, so a page of two would satisfy an assertion about a
         *     population of fifty.
         */
        GuestbookEntryPage: {
            /** Items */
            items: components["schemas"]["GuestbookEntryRead"][];
            /** Total */
            total: number;
            /** Total All */
            total_all: number;
        };
        /**
         * GuestbookEntryRead
         * @description Response contract for a single guestbook entry.
         */
        GuestbookEntryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Author */
            author: string;
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GuestbookEntrySort
         * @description The orders the list may be read in (`BR-04`).
         *
         *     A closed set rather than a free string, so an unknown value is a refusal the
         *     caller can act on instead of a silent fall back to the default -- a client
         *     that misspells `oldest` should learn it, not get the newest first and
         *     quietly disagree with what its screen says.
         *
         *     `StrEnum` so FastAPI renders the two values into the OpenAPI document as an
         *     enum of strings, which is what makes them reachable from the generated
         *     frontend types -- and so a member compares equal to its own wire value,
         *     which is what lets a step or a test say `"newest"` and mean the member.
         * @enum {string}
         */
        GuestbookEntrySort: "newest" | "oldest";
        /**
         * GuestbookEntryUpdate
         * @description Request contract for `PATCH /api/guestbook-entries/{entry_id}`.
         *
         *     Both fields are optional and a body that sets neither is refused by the
         *     router, not here: "no field given" is a fact about the request, and the
         *     sentence the operator reads about it belongs beside the endpoint that
         *     produced it (spec/design/conventions.md § Layers).
         */
        GuestbookEntryUpdate: {
            /** Author */
            author?: string | null;
            /** Message */
            message?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthRead
         * @description What the probe answers with when the process is up.
         *
         *     `status` is always `"ok"` and typed as a plain string rather than a literal
         *     on purpose: this endpoint's whole design is that answering at all IS the
         *     signal (`app/platform/routers/health.py`), so a second value would be a different
         *     endpoint. It is kept in the body because that is what every caller already
         *     keys on -- `scripts/app_status.py` among them.
         *
         *     `environment` and `version` say WHICH copy answered. Without them a probe
         *     that returns 200 proves something is alive and nothing about what it is,
         *     which is the question actually asked after a release.
         */
        HealthRead: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Version */
            version: string;
        };
        /**
         * Refusal
         * @description The envelope FastAPI puts a raised `HTTPException.detail` into.
         */
        Refusal: {
            detail: components["schemas"]["RefusalDetail"];
        };
        /**
         * RefusalDetail
         * @description The code, the sentence, and the identifier the refusal is about.
         */
        RefusalDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Id */
            id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRead"];
                };
            };
        };
    };
    list_guestbook_entries_api_guestbook_entries_get: {
        parameters: {
            query?: {
                /** @description Narrow to entries containing this. */
                q?: string | null;
                /** @description Which end of the book to read from. */
                sort?: components["schemas"]["GuestbookEntrySort"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestbookEntryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_guestbook_entry_api_guestbook_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestbookEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestbookEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_guestbook_entry_api_guestbook_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestbookEntryRead"];
                };
            };
            /** @description There is no entry with that identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_guestbook_entry_api_guestbook_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description There is no entry with that identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_guestbook_entry_api_guestbook_entries__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestbookEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestbookEntryRead"];
                };
            };
            /** @description There is no entry with that identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description The body sets no field at all, or a field is outside its bounds. Two different shapes under one status code: a coded refusal for the first, FastAPI's validation error for the rest. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
